spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 25032004

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  sendgrid:
    api-key: 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
    from-email: ktuan2503@gmail.com
    template-id: d-8d276ce816254b399ebcc962d2f2199a
    verification-link: http://localhost:8080/user/confirm-email

# application-dev.yml
# swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  expiryMinutes: 5
  expiryDay: 14
  accessKey: IIwLeRIVsznVTPFEYmA6HiVVBrlKkKqC36OpWzqw8mk=
  refreshKey: tvszknimPZQEdy3c9TCERBLAkOyoCc2ZvOmGcHsRJgg=

